# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bb22d2394e84d58d2bfa8c1e2586672d921272fe462eacc47970e8b149f0d35492efb1b774cecd17f4de4260acb29414c6c77ee848041014a328f450e14015a

test:
  secret_key_base: 2c105d774c024754d8fd2419398cbd77072f536f94c72e02d77eb3cbf1f24b931c3c18f3ce2dc5b83da952a0b7b72e250346da4ed0f76fd80859d588a1a6a1fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
